<?php
    include("templates/header.php");
    include("templates/sidePanel.php");
    include("templates/hero.php");
    include("templates/info.php");
    include("templates/advert.php");
    include("templates/benefits.php");
?>
</body>
</html>
